### ISSUE TITLE
Daily Reward Tasks Not Opening

### ISSUE THREAD

**Issue by ChippewaBarr** [h4x0rm1k3/ABS#1]
A few days ago the Daily Rewards Tasks function stopped working...searches still complete as normal though.

May need to revise the code for the Daily Rewards Tasks portion. Was working great till then.

**Comment by Filaipus** [comment]
I have the same issue. @h4x0rm1k3 I saw you setup a "buy me a coffe" for yourself, are you planning on maintaining ABS or you just wanted to give people instructions on how to install it now that it's off the chrome store?

**Comment by h4x0rm1k3** [comment]
Hi both, (sorry for the late reply @ChippewaBarr , I've only just seen the message from @Filaipus ). Strangely, myself or my friend who also uses the add-on don't have this issue, and our accounts run perfectly and rack up points normally. The only thing I can think of is that maybe you're not leaving the windows open long enough? I found that leaving them open for around 10 minutes after they've finished seems to then give all green ticks in the reward's page, so it's possible that's what your issue is? Do the rewards pages at least open for you still and appear to be doing their job in clicking things for you? 

I took up maintaining the add-on myself as the original version stopped working but since I last updated on Git it's been working fine my end like I said so am not sure exactly what's happening your ends. If you could maybe explain a little more about what's happening etc I'll have a look and see if I can spot anything that may be causing it. The Buy me a coffee I did change to my link as I took up maintaining it as it didn't look as though the original owner was updating it anymore, it's not a must do thing, it's only there purely if people feel like donating a little as I earn a fair bit from using the add-on myself anyway so it pays for itself really!

**Comment by ChippewaBarr** [comment]
Hey thanks for responding.

Definitely not an issue of leaving the windows open as I wake my PC daily to open Chrome and let it do it's thing and maybe not come back for like an hour or more.

Basically what happens as soon as I open Chrome is that the Rewards Page opens, along with a tab for the searches (which complete as per normal). The issue is on the Rewards Page (where you can see the Rewards Tasks) where they don't open their own tabs/windows to run through the quizzes.

I think it has to do with something about opening the Rewards Tasks because if I open them manually, they will auto-click themselves through the quizzes, but without me manually opening them (in the same window or a new tab) nothing happens.

Even selecting Open Rewards Tasks from the extension button it simply opens the Rewards Page, and not the tasks themselves.

I'll try removing it and adding it back, but take a look on your end if you can.

**Comment by h4x0rm1k3** [comment]
Very, very strange then 'cos I checked all 36 accounts I run this morning after they'd completed overnight and every single one of them completed the rewards section as well as the searches but I think searches will always run regardless anyway as they did last time it broke! My mate has 6  accounts that don't open up the rewards pages and we can't figure out why that is but maybe it's something to do with what you're experiencing, those accounts have always been like that though and never behaved like they should but I think that's probably something different to what you're experiencing 'cos yours used to run fine at one point whereas his never did! His accounts also work like yours whereby if he opens the rewards tabs manually then ABS will take over and complete them without issue. One thing to try when you've got to click rewards through ABS itself is as soon as the rewards page shows it's contents click the open rewards button again and see if that'll open up the pages as i've had to do that a couple of times myself in the past to speed things along a little quicker if i'm 'babysitting' the accounts at anytime.
Any chance you can run a test for me by making an account completely fresh, create a new user in Chrome and set up ABS on it and see if that works properly at all? I'm hoping that the outcome is that it works like it should do as I literally made 6 new accounts about 5 days ago and all of them run as they should do.

**Comment by ChippewaBarr** [comment]
So I removed the extension completely and redownloaded the `src` and set it back up and it seems to be working now again...mostly.

Not sure what changed but simply removing and re-adding has made it so opening Chrome, then my user profile, will allow the Reward Tasks to open each of themselves and run. 

Some odd things still persist like I still have the `?redref=amc` at the end of the URL, and if I click the Open Rewards Task button in the extension, it still only opens the page, rather than the page and all the tasks...so hopefully it stays working despite these oddities.

Side question: what are you doing with the 36 accounts? As far as I know you can't pool the points together onto one account can you? Or do you just redeem for things like gift cards and simply use their codes on your "main" account?

**Comment by h4x0rm1k3** [comment]
Yes the ?redref=amc became a thing when I 1st took it over, then the following month it was a problem with opening the rewards  box's themselves and since then it's been good for me. As I said, my friend does have a set that seems to play similar games with him so i'll see if at some point I can get it running on his PC and then let you know how I done it and see if it fixes it your end also. Have you tried pressing the open rewards task button a second time once you see the 1st sign of the rewards page loading up, I find on the odd occasion when I check in the morning 1 or 2 of mine haven't opened rewards page at all so I click that button twice, once to refresh it and then just as you see the page start to load press it again and it 'should' open the tabs. Accounts points are useful for a number of things really but main ones you've already mentioned without saying too much!

**Comment by Filaipus** [comment]
I reinstalled and it's now opening properly (in some cases). I'll try it for a few days and let you know if there's any problems with it.

**Comment by h4x0rm1k3** [comment]
I'm going to close this issue as it was only you 2 that had the issue and all seems working on mine and another PC. Also it seems like uninstalling the add on and then re-installing it again seems to work. If needs be in the future it can either be moved back or a new issue ticket created.
